### ISSUE TITLE
Non existing images referenced

### ISSUE THREAD

**Issue by Susticle** [PanoptikumIO/pan#47]
In podcast/episode data images are referenced which are not referenced in the current feed data (any more?).

An example is:
https://panoptikum.io/podcasts/46994

Via API I get references to:
- https://uebergabe-podcast.de/wp-content/uploads/2018/12/Uebergabe-Logo-5.jpg (twice)
- https://uebergabe-podcast.de/wp-content/uploads/2019/03/Uebergabe_eHealth_Podcast.jpg
- https://uebergabe-podcast.de/wp-content/uploads/2018/10/U%CC%88bergabe-Logo-5.jpg

I also did a metadata update but the problem persists.

The references do not exist in the current feed:
https://uebergabe.de/podcast/feed/mp3/

**Comment by haslinger** [comment]
That is definitely a bug. Episode thumbnails are always cached, so a reference to an external domain is a bug. Things I have to do:

* Find all instances of external paths.
* Delete them and reset the boolean ```thumbnailed```, so that their thumbnails will be retrieved again
* Double check, if they are then working or if there is a bug inherent in the thumbnail retrieval (There must be, because who could they show up at all?).

**Comment by haslinger** [comment]
We do not check for outdated images of podcasts or episodes, as that would be +5 000 000 requests for runs. That's the reason for having the images cached.

The weird looking image in [Episode 4231192](https://panoptikum.io/episodes/4231192) has actually been retrieved from the original domain that way.

The metadata update does not touch episodes that are not in the feed any more. The reason is that some feeds, e.g. Omegataupodcast, only hold the last x episodes in the feed and also don't have older episodes in a paged feed. So we would loose information about the old episodes. The side effect of that is, that episodes, that have been taken down completely, along side with their images, are still in Panoptikum. 

So I do not see a way to fix that behaviour  currently. Maybe let's discuss that further (on Twitter?)

**Comment by haslinger** [comment]
Metadata update from now on deletes image urls from episodes when they are no longer in the feed.
The orig-image-url in the json-api request to an episode is then empty.
The image title stays filled (used for image thumbnails).
